apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-env"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
stringData:
  DB_HOSTNAME: {{ .Values.secrets.dbHostname }}
  DB_postgrespg_NAME: {{ .Values.secrets.dbName }}
  DB_USERNAME: {{ .Values.secrets.dbUsername }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
