apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgrespg"
  labels:
    app: "{{ .Release.Name }}-postgrespg"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: "{{ .Release.Name }}-postgrespg"
  ports:
    - name: tcp-postgresql
      port: {{ .Values.service.port }}
      targetPort: 5432
